backend/accounts/urls.py
from django.urls import path
from .views import SignUpView, SignInView, SignOutView, ProfileView


app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="sign_up"),
    path("signin/", SignInView.as_view(), name="sign_in"),
    path("signout/", SignOutView.as_view(), name="sign_out"),
    path("profile/<slug:slug>", ProfileView.as_view(), name="profile"),
]

backend/posts/urls.py
from django.urls import path
from .views import (
    PostCreateView,
    PostIndexView,
    PostDetailView,
    voteView,
    PostEditView,
    CommentEditView,
    PostDeleteView,
    CommentDeleteView,
    SearchView,
)


app_name = "posts"
urlpatterns = [
    path("", PostIndexView.as_view(), name="index"),
    path("threads/new/", PostCreateView.as_view(), name="create"),
    path("threads/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path(
        "threads/<int:post_id>/<int:id>/<int:content_type>/<int:vote_type>/<str:redir>/",
        voteView,
        name="vote",
    ),
    path("threads/<int:pk>/edit/", PostEditView.as_view(), name="edit"),
    path(
        "threads/<int:t_pk>/<int:pk>/edit/",
        CommentEditView.as_view(),
        name="edit_comment",
    ),
    path("threads/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path(
        "threads/<int:t_pk>/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="delete_comment",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

backend/threadmill/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("posts.urls")),
]

backend/posts/forms.py
from django import forms
from .models import Post, Comment


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

    def clean(self):
        cleaned_data = super().clean()

        # Unallow spaces only.
        title = cleaned_data.get("title")
        if len(str(title).strip()) == 0:
            self.add_error("title", "Please fill in the title.")

        # Unallow spaces only.
        content = cleaned_data.get("content")
        if len(str(content).strip()) == 0:
            self.add_error("content", "Please fill in the content.")

        return cleaned_data


class PostDetailForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

    def clean(self):
        cleaned_data = super().clean()

        # Unallow spaces only.
        content = cleaned_data.get("content")
        if len(str(content).strip()) == 0:
            self.add_error("content", "Please fill in the content.")

        return cleaned_data


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

    def clean(self):
        cleaned_data = super().clean()

        # Unallow spaces only.
        title = cleaned_data.get("title")
        if len(str(title).strip()) == 0:
            self.add_error("title", "Please fill in the title.")

        # Unallow spaces only.
        content = cleaned_data.get("content")
        if len(str(content).strip()) == 0:
            self.add_error("content", "Please fill in the content.")

        return cleaned_data


class CommentEditForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

    def clean(self):
        cleaned_data = super().clean()

        # Unallow spaces only.
        content = cleaned_data.get("content")
        if len(str(content).strip()) == 0:
            self.add_error("content", "Please fill in the content.")

        return cleaned_data


class SearchForm(forms.Form):
    search = forms.CharField(max_length=80)

backend/posts/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    FormView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.contrib.auth import get_user_model
from .models import Post, Comment, Vote
from .forms import (
    PostDetailForm,
    PostCreateForm,
    PostEditForm,
    CommentEditForm,
    SearchForm,
)
from django.db.models import Q
from django.db import models
from django.contrib.auth.mixins import LoginRequiredMixin


def get_has_voted_data(post_or_comment_list, user=None):
    """
    Helper function to check if user has voted. Given a list of posts or a list of comments, returns
    a list of upvote and downvote html class based on user vote status.
    """

    upvote_class_list = {}
    downvote_class_list = {}

    for object in post_or_comment_list:
        upvote_class_list[object.id] = "link-secondary"
        downvote_class_list[object.id] = "link-secondary"

        if user is not None:
            # Check if the user has voted.
            if user.is_authenticated:
                try:
                    vote = object.votes.get(voter__exact=user)
                    if vote:
                        if vote.vote_type:
                            upvote_class_list[object.id] = "link-success"
                        else:
                            downvote_class_list[object.id] = "link-danger"
                except:
                    pass

    return upvote_class_list, downvote_class_list


class PostIndexView(ListView):
    template_name = "posts/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user

        # Get votes data.
        upvotes, downvotes = get_has_voted_data(self.object_list, user)
        context["upvote_class"] = upvotes
        context["downvote_class"] = downvotes

        # Get comment count for each post.
        comment_count_list = {}
        for post in self.object_list:
            comment_count_list[post.id] = post.comments.count()
        context["comment_count_list"] = comment_count_list

        return context

    def get_queryset(self) -> QuerySet[Any]:
        # Most popular first.
        return Post.objects.order_by("-vote_rating", "-pub_date")


class PostCreateView(FormView):
    template_name = "posts/post_create.html"
    form_class = PostCreateForm
    success_url = reverse_lazy("posts:index")

    def form_valid(self, form: PostCreateForm) -> HttpResponse:
        if self.request.user.is_authenticated:
            post = form.save(commit=False)
            post.author = self.request.user
            post.save()
            return super().form_valid(form)
        else:
            form.add_error("title", "Please sign in to post.")
            return super().form_invalid(form)


class PostDetailView(FormMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    form_class = PostDetailForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user

        # Get votes data for the post.
        upvotes, downvotes = get_has_voted_data([self.object], user)
        context["upvote_class"] = upvotes[self.object.pk]
        context["downvote_class"] = downvotes[self.object.pk]

        # Get votes data for the all the comments.
        upvotes, downvotes = get_has_voted_data(self.object.comments.all(), user)
        context["comments_upvote_class"] = upvotes
        context["comments_downvote_class"] = downvotes

        # Get all comments.
        context["comments"] = self.object.comments.order_by("-vote_rating", "-pub_date")

        return context

    def get_success_url(self):
        return reverse("posts:detail", kwargs={"pk": self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form = self.get_form()
        if form.is_valid() and self.request.user.is_authenticated:
            return self.form_valid(form)
        else:
            form.add_error("content", "Please sign in to comment.")
            return self.form_invalid(form)

    def form_valid(self, form: PostDetailForm) -> HttpResponse:
        if self.request.user.is_authenticated:
            comment = form.save(commit=False)
            comment.parent_object = Post.objects.get(pk=self.kwargs.get("pk"))
            comment.author = self.request.user
            comment.save()
            return super().form_valid(form)
        else:
            form.add_error("content", "Please sign in to comment.")
            return super().form_invalid(form)


def voteView(request, post_id, id, content_type, vote_type, redir):
    # content_type 0 = Post, 1 = Comment
    if not content_type:
        object = get_object_or_404(Post, pk=id)
    else:
        object = get_object_or_404(Comment, pk=id)

    user = request.user
    if user.is_authenticated:
        # Don't allow self-voting.
        if user == object.author:
            messages.error(request, "You can vote for yourself!")
            if redir == "posts:detail":
                return redirect(reverse(redir, args=(post_id,)))
            else:
                return redirect(reverse(redir))

        try:
            vote = object.votes.get(voter__exact=user)
            # The user has already voted.

            # Upvoted.
            if vote.vote_type:
                if vote_type:
                    # User already upvoted. So, remove the vote.
                    vote.delete()
                else:
                    # Change to downvote.
                    vote.vote_type = False
                    vote.save()
            # Downvoted.
            else:
                if not vote_type:
                    # User already downvoted. So, remove the vote.
                    vote.delete()
                else:
                    # Change to upvote.
                    vote.vote_type = True
                    vote.save()

            if redir == "posts:detail":
                return redirect(reverse(redir, args=(post_id,)))
            else:
                return redirect(reverse(redir))
        except (KeyError, Vote.DoesNotExist):
            # The user haven't voted.
            new_vote = Vote(vote_type=bool(vote_type), voter=user, voted_object=object)
            new_vote.save()

            if redir == "posts:detail":
                return redirect(reverse(redir, args=(post_id,)))
            else:
                return redirect(reverse(redir))
    else:
        # User not logged in.
        messages.error(request, "You must be logged in to do that.")
        if redir == "posts:detail":
            return redirect(reverse(redir, args=(post_id,)))
        else:
            return redirect(reverse(redir))


class PostEditView(UpdateView):
    model = Post
    template_name = "posts/post_edit.html"
    form_class = PostEditForm

    def get_success_url(self, **kwargs):
        return reverse_lazy("posts:detail", kwargs={"pk": self.kwargs.get("pk")})

    def form_valid(self, form: PostEditForm) -> HttpResponse:
        if self.request.user.is_authenticated:
            if self.request.user == self.object.author:
                self.object.save()
                return super().form_valid(form)
            else:
                form.add_error("title", "You don't own the thread.")
                form.add_error("content", "You don't own the thread.")
                return super().form_invalid(form)
        else:
            form.add_error("title", "Please sign in to edit.")
            return super().form_invalid(form)


class CommentEditView(UpdateView):
    model = Comment
    template_name = "posts/comment_edit.html"
    form_class = CommentEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = Post.objects.get(id=self.kwargs.get("t_pk"))
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy("posts:detail", kwargs={"pk": self.kwargs.get("t_pk")})

    def form_valid(self, form: CommentEditForm) -> HttpResponse:
        if self.request.user.is_authenticated:
            if self.request.user == self.object.author:
                self.object.save()
                return super().form_valid(form)
            else:
                form.add_error("title", "You don't own the comment.")
                form.add_error("content", "You don't own the comment.")
                return super().form_invalid(form)
        else:
            form.add_error("title", "Please sign in to edit.")
            return super().form_invalid(form)


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("accounts:sign_in")
    model = Post
    success_url = reverse_lazy("posts:index")

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(request, "You must be logged in to do that.")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form: Any) -> HttpResponse:
        # the Post object
        object = self.get_object()
        if object.author == self.request.user:
            success_url = self.get_success_url()
            object.delete()
            return redirect(success_url)
        else:
            messages.error(self.request, "The thread does not belong to you.")
            return redirect(reverse("posts:detail", args=(self.kwargs.get("pk"),)))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("accounts:sign_in")
    model = Comment

backend/posts/templates/posts/comment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Delete{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        <h3 class="text-center m-4">Deleting comment in <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' object.parent_object.id %}">{{ object.parent_object.title }}</a></h3>

        {% if user.is_authenticated %}

        <div class="row card my-4 shadow">
            <div class="card-header text-body-secondary py-0 px-2 d-flex">
                <span class="ms-auto">{{ object.vote_rating }} <i class="bi bi-stars"></i></span>
            </div>
            <div class="card-body">
                <h6 class="card-subtitle mb-2 text-body-secondary">
                    <a class="link-underline link-underline-opacity-0" href="{% url 'accounts:profile' object.author.slug %}">{{ object.author.username }}</a>
                </h6>
                <p class="card-text">{{ object.content }}</p>
            </div>
            <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                <span class="ms-auto">{{ object.pub_date }}</span>
            </div>
        </div>

        <div class="row card my-4 shadow py-2">
            <form class="form-inline d-flex" method="post">{% csrf_token %}
                <p>Are you sure you want to delete this?</p>
                <input class="btn btn-primary ms-auto" type="submit" value="Confirm">
            </form>
        </div>

        {% else %}
        <div class="row my-4 shadow p-4 text-center">Please sign in to delete.</div>
        {% endif %}
        
    </div>
</div>

{% endblock content %}

backend/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Home{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        {% if messages %}
        {% for message in messages %}
        {% comment %} {% if not "search_form_value" in message.tags %} {% endcomment %}
        <div class="row card my-2 border-danger">
            <div class="card-body">
                <p class="card-text">{{ message }}</p>
            </div>
        </div>
        {% comment %} {% endif %} {% endcomment %}
        {% endfor %}
        {% endif %}

        {% if post_list %}
            {% load template_filters %}

            {% for p in post_list %}
            <div class="row card my-4 shadow">
                <div class="card-header text-body-secondary py-0 px-2 d-flex">
                    
                    {% if not p.author == user %}

                        <a class="{{ upvote_class|dict_lookup:p.id }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' p.id p.id 0 1 'posts:index' %}"><i class="bi bi-hand-thumbs-up mx-1"> Upvote</i></a>
                        <a class="{{ downvote_class|dict_lookup:p.id }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' p.id p.id 0 0 'posts:index' %}"><i class="bi bi-hand-thumbs-down mx-1"> Downvote</i></a>
                    
                    {% endif %}

                    <span class="ms-auto">{{ p.vote_rating }} <i class="bi bi-stars"></i></span>
                
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' p.id %}">{{ p.title }}</a>
                    </h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        <a class="link-underline link-underline-opacity-0" href="{% url 'accounts:profile' p.author.slug %}">{{ p.author.username }}</a>
                    </h6>
                </div>
                <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                    <i class="bi bi-chat-left-text mx-2"></i>
                    <span>{{ comment_count_list|dict_lookup:p.id }}</span>

                    {% if user.is_authenticated and p.author == user %}
                        <i class="bi bi-pencil-square mx-2"></i>
                        <a class="link-underline link-underline-opacity-0 p-0 m-0" href="{% url 'posts:edit' p.id %}">Edit</a>

                        <i class="bi bi-x-square mx-2"></i>
                        <form class="form-inline p-0 m-0 d-flex" id="deleteForm" action="{% url 'posts:delete' p.id %}" method="get">
                            {% csrf_token %}
                            <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteForm').submit();" style="cursor: pointer;">Delete</a>
                        </form>
                        {% comment %} <a class="link-underline link-underline-opacity-0" href="{% url 'posts:delete' p.id %}">Delete</a> {% endcomment %}
                    {% endif %}

                    <span class="ms-auto">{{ p.pub_date }}</span>
                </div>
            </div>
            {% endfor %}

        {% else %}
            <div class="row my-4 shadow p-4 text-center">Looks like there isn't anything here.</div>
        {% endif %}

    </div>
</div>
{% endblock content %}

backend/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}ThreadMill - {{ post.title }}{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        {% if messages %}
        {% for message in messages %}
        {% comment %} {% if not "search_form_value" in message.tags %} {% endcomment %}
        <div class="row card my-2 border-danger">
            <div class="card-body">
                <p class="card-text">{{ message }}</p>
            </div>
        </div>
        {% comment %} {% endif %} {% endcomment %}
        {% endfor %}
        {% endif %}

        {% comment %} Post {% endcomment %}

        <div class="row card my-4 shadow">
            <div class="card-header text-body-secondary py-0 px-2 d-flex">

                {% if not post.author == user %}

                <a class="{{ upvote_class }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' post.id post.id 0 1 'posts:detail' %}"><i class="bi bi-hand-thumbs-up mx-1"> Upvote</i></a>
                <a class="{{ downvote_class }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' post.id post.id 0 0 'posts:detail' %}"><i class="bi bi-hand-thumbs-down mx-1"> Downvote</i></a>
                
                {% endif %}
                
                <span class="ms-auto">{{ post.vote_rating }} <i class="bi bi-stars"></i></span>
            </div>
            <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h3>
                <h6 class="card-subtitle mb-2 text-body-secondary">
                    <a class="link-underline link-underline-opacity-0" href="{% url 'accounts:profile' post.author.slug %}">{{ post.author.username }}</a>
                </h6>
                <p class="card-text">{{ post.content }}</p>
            </div>
            <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                {% if user.is_authenticated and post.author == user %}
                    <i class="bi bi-pencil-square mx-2"></i>
                    <a class="link-underline link-underline-opacity-0" href="{% url 'posts:edit' post.id %}">Edit</a>

                    <i class="bi bi-x-square mx-2"></i>
                    <form class="form-inline p-0 m-0 d-flex" id="deleteForm" action="{% url 'posts:delete' post.id %}" method="get">
                        {% csrf_token %}
                        <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteForm').submit();" style="cursor: pointer;">Delete</a>
                    </form>
                {% endif %}

                <span class="ms-auto">{{ post.pub_date }}</span>
            </div>
        </div>

        {% comment %} End of Post {% endcomment %}

        {% comment %} Comments {% endcomment %}

        {% for comment in comments %}

        <div class="row my-4">

            <div class="col-auto">
                <i class="bi bi-chat-left-text"></i>
            </div>

            <div class="col card shadow m-0 p-0">
                <div class="card-header text-body-secondary py-0 px-2 d-flex">
                    
                    {% load template_filters %}

                    {% if not comment.author == user %}

                    <a class="{{ comments_upvote_class|dict_lookup:comment.id }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' post.id comment.id 1 1 'posts:detail' %}"><i class="bi bi-hand-thumbs-up mx-1"> Upvote</i></a>
                    <a class="{{ comments_downvote_class|dict_lookup:comment.id }} link-underline link-underline-opacity-0" href="{% url 'posts:vote' post.id comment.id 1 0 'posts:detail' %}"><i class="bi bi-hand-thumbs-down mx-1"> Downvote</i></a>
                    
                    {% endif %}
                    
                    <span class="ms-auto">{{ comment.vote_rating }} <i class="bi bi-stars"></i></span>
                
                </div>
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-body-secondary">
                        <a class="link-underline link-underline-opacity-0" href="{% url 'accounts:profile' comment.author.slug %}">{{ comment.author.username }}</a>
                    </h6>
                    <p class="card-text">{{ comment.content }}</p>
                </div>
                <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                    {% if user.is_authenticated and comment.author == user %}
                        <i class="bi bi-pencil-square mx-2"></i>
                        <a class="link-underline link-underline-opacity-0" href="{% url 'posts:edit_comment' post.id comment.id %}">Edit</a>

                        <i class="bi bi-x-square mx-2"></i>
                        <form class="form-inline p-0 m-0 d-flex" id="deleteCommentForm" action="{% url 'posts:delete_comment' post.id comment.id %}" method="get">
                            {% csrf_token %}
                            <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteCommentForm').submit();" style="cursor: pointer;">Delete</a>
                        </form>
                    {% endif %}
                    
                    <span class="ms-auto">{{ comment.pub_date }}</span>
                </div>
            </div>

        </div>

        {% endfor %}

        {% comment %} End of Comments {% endcomment %}

        <div class="row card my-4 py-4 px-2 shadow">
            <h5 class="text-center">
                <i class="bi bi-chat-left-text"></i>
                Leave a comment
            </h5>
            <form action="" method="post">
                {% csrf_token %}
                
                <div class="form-floating my-3">
                    {% if form.content.value %}
                    {% if form.content.errors %}
                    <textarea style="height: 300px" class="form-control is-invalid" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" placeholder="" required>{{ form.content.value }}</textarea>
                    <div class="invalid-feedback">{{ form.content.errors.0 }}</div> 
                    {% else %}
                    <textarea style="height: 300px" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" placeholder="" required>{{ form.content.value }}</textarea>
                    {% endif %}
                    {% else %}
                    <textarea style="height: 300px" class="form-control" id="{{ form.content.id_for_label }}" name="{{ form.content.html_name }}" placeholder="" required></textarea>
                    {% endif %}
                    <label for="{{ form.content.id_for_label }}">Comment</label>
                </div>
                
                <input class="btn btn-primary" type="submit" value="Comment">
                
            </form>
        </div>
    </div>
</div>
{% endblock content %}

backend/posts/templates/posts/search.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Search{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        {% if messages %}
        {% for message in messages %}
        <div class="row card my-2 border-danger">
            <div class="card-body">
                <p class="card-text">{{ message }}</p>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        {% if hits %}
            {% load template_filters %}
            {% for hit in hits %}
            <div class="row my-4">
                {% if hit.title == None %}
                <div class="col-auto">
                    <i class="bi bi-chat-left-text"></i>
                </div>
                {% endif %}

                <div class="col card shadow m-0 p-0">
                    <div class="card-header text-body-secondary py-0 px-2 d-flex">
                        {% if hit.title == None %}
                        <span class="ms-2 me-1">...</span>
                        <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' comments|get_comment_parent_object_id:hit.id %}"> {{ comments|get_comment_parent_object_title:hit.id }}</a>
                        {% endif %}
                        <span class="ms-auto">{{ hit.vote_rating }} <i class="bi bi-stars"></i></span>
                    </div>
                    <div class="card-body">
                        {% if hit.title != None %}
                        <h5 class="card-title">
                            <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' hit.id %}">{{ hit.title }}</a>
                        </h5>
                        {% endif %}
                        <h6 class="card-subtitle mb-2 text-body-secondary">{{ hit.author.username }}</h6>
                        {% if hit.title == None %}
                        <p class="card-text">{{ hit.content }}</p>
                        {% endif %}
                    </div>
                    <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                        {% if hit.title != None %}
                        <i class="bi bi-chat-left-text mx-2"></i>
                        <span>{{ comment_count_list|dict_lookup:hit.id }}</span>
                        {% endif %}

                        {% if user.is_authenticated and hit.author == user %}

                            {% if hit.title != None %}

                                <i class="bi bi-pencil-square mx-2"></i>
                                <a class="link-underline link-underline-opacity-0 p-0 m-0" href="{% url 'posts:edit' hit.id %}">Edit</a>

                                <i class="bi bi-x-square mx-2"></i>
                                <form class="form-inline p-0 m-0 d-flex" id="deleteForm" action="{% url 'posts:delete' hit.id %}" method="get">
                                    {% csrf_token %}
                                    <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteForm').submit();" style="cursor: pointer;">Delete</a>
                                </form>

                            {% else %}
                            
                                <i class="bi bi-pencil-square mx-2"></i>
                                <a class="link-underline link-underline-opacity-0" href="{% url 'posts:edit_comment' comments|get_comment_parent_object_id:hit.id hit.id %}">Edit</a>
        
                                <i class="bi bi-x-square mx-2"></i>
                                <form class="form-inline p-0 m-0 d-flex" id="deleteCommentForm" action="{% url 'posts:delete_comment' comments|get_comment_parent_object_id:hit.id hit.id %}" method="get">
                                    {% csrf_token %}
                                    <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteCommentForm').submit();" style="cursor: pointer;">Delete</a>
                                </form>
                            
                            {% endif %}


                        {% endif %}

                        <span class="ms-auto">{{ hit.pub_date }}</span>
                    </div>
                </div>
            </div>
            {% endfor %}

        {% else %}
        <div class="row my-4 shadow p-4 text-center">No results matching your search were found.</div>
        {% endif %}

    </div>
</div>
{% endblock content %}