backend/accounts/urls.py
from django.urls import path
from .views import SignUpView, SignInView, SignOutView, ProfileView


app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="sign_up"),
    path("signin/", SignInView.as_view(), name="sign_in"),
    path("signout/", SignOutView.as_view(), name="sign_out"),
    path("profile/<slug:slug>", ProfileView.as_view(), name="profile"),
]

backend/posts/urls.py
from django.urls import path
from .views import (
    PostCreateView,
    PostIndexView,
    PostDetailView,
    voteView,
    PostEditView,
    CommentEditView,
    PostDeleteView,
    CommentDeleteView,
    SearchView,
)


app_name = "posts"
urlpatterns = [
    path("", PostIndexView.as_view(), name="index"),
    path("threads/new/", PostCreateView.as_view(), name="create"),
    path("threads/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path(
        "threads/<int:post_id>/<int:id>/<int:content_type>/<int:vote_type>/<str:redir>/",
        voteView,
        name="vote",
    ),
    path("threads/<int:pk>/edit/", PostEditView.as_view(), name="edit"),
    path(
        "threads/<int:t_pk>/<int:pk>/edit/",
        CommentEditView.as_view(),
        name="edit_comment",
    ),
    path("threads/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path(
        "threads/<int:t_pk>/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="delete_comment",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

backend/threadmill/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("posts.urls")),
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from unidecode import unidecode


class User(AbstractUser):
    email = models.EmailField(max_length=50, primary_key=True)
    # username is the displayed name.
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=30)
    slug = models.SlugField(default="", null=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.username))
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.slug

backend/accounts/forms.py
from typing import Any, Dict
from django import forms
from django.contrib.auth import get_user_model


class SignUpForm(forms.ModelForm):
    username = forms.CharField(min_length=4, max_length=30, widget=forms.TextInput)
    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput)
    confirm_password = forms.CharField(
        min_length=8, max_length=30, widget=forms.PasswordInput
    )

    class Meta:
        model = get_user_model()
        fields = ["username", "email", "password"]

    def clean(self) -> Dict[str, Any]:
        cleaned_data = super().clean()

        # Password validation via repeating password.
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password and confirm_password and password != confirm_password:
            self.add_error("password", "Passwords do not match.")
            self.add_error("confirm_password", "Passwords do not match.")

        # Only alphanumeric.
        username = cleaned_data.get("username")
        if not str(username).isalnum():
            self.add_error("username", "Please enter only alphanumerics.")

        return cleaned_data


class SignInForm(forms.Form):
    login_cred = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

backend/accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, RedirectView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, SignInForm
from posts.models import Post, Comment, Vote
from django.db.models import Q


class SignUpView(FormView):
    template_name = "accounts/sign_up.html"
    form_class = SignUpForm
    success_url = reverse_lazy("accounts:sign_in")

    def form_valid(self, form: SignUpForm) -> HttpResponse:
        user = form.save(commit=False)
        # Obscure password before saving into database.
        user.set_password(form.cleaned_data["password"])
        user.save()
        messages.success(self.request, "Sign up successful!")
        return super().form_valid(form)


class SignInView(FormView):
    template_name = "accounts/sign_in.html"
    form_class = SignInForm
    success_url = reverse_lazy("posts:index")

    def form_valid(self, form: SignInForm) -> HttpResponse:
        login_cred = form.cleaned_data.get("login_cred")
        password = form.cleaned_data.get("password")

        # authenticate overriden by custom authentication backend.
        user = authenticate(self.request, username=login_cred, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            form.add_error("login_cred", "Incorrect login details.")
            form.add_error("password", "Incorrect login details.")
            return super().form_invalid(form)


class SignOutView(RedirectView):
    url = reverse_lazy("posts:index")

    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        messages.success(self.request, "Signed out.")
        return super().get_redirect_url(*args, **kwargs)


class ProfileView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("accounts:sign_in")
    model = get_user_model()
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.get_object()

        posts = Post.objects.filter(author=user).order_by("-pub_date")
        context["posts"] = posts

        # Get comment count for each post.
        comment_count_list = {}
        for post in posts:
            comment_count_list[post.id] = post.comments.count()
        context["comment_count_list"] = comment_count_list

        comments = Comment.objects.filter(author=user).order_by("-pub_date")
        context["comments"] = comments

        votes = Vote.objects.filter(voter=user).order_by("-date_order")
        context["votes"] = votes

        # Make sure the user context holds the authenticated user instead of the object.
        context["user"] = self.request.user

        return context

backend/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Profile{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        {% if messages %}
        {% for message in messages %}
        {% comment %} {% if not "search_form_value" in message.tags %} {% endcomment %}
        <div class="row card my-2 border-danger">
            <div class="card-body">
                <p class="card-text">{{ message }}</p>
            </div>
        </div>
        {% comment %} {% endif %} {% endcomment %}
        {% endfor %}
        {% endif %}

        {% if user.is_authenticated %}

        <div class="row card my-4 pt-3 py-2 ps-1 border-primary-subtle">
            <h4>{{ object.username }}'s Profile</h4>
        </div>

        <div class="row my-2">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="threads-tab" data-bs-toggle="tab" data-bs-target="#threads-tab-pane" type="button" role="tab" aria-controls="threads-tab-pane" aria-selected="true">Threads</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="comments-tab" data-bs-toggle="tab" data-bs-target="#comments-tab-pane" type="button" role="tab" aria-controls="comments-tab-pane" aria-selected="false">Comments</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="votes-tab" data-bs-toggle="tab" data-bs-target="#votes-tab-pane" type="button" role="tab" aria-controls="votes-tab-pane" aria-selected="false">Votes</button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">

                {% comment %} Threads {% endcomment %}

                <div class="tab-pane fade show active" id="threads-tab-pane" role="tabpanel" aria-labelledby="threads-tab" tabindex="0">

                {% if posts %}
                    {% load template_filters %}

                    {% for post in posts %}
                    <div class="row card my-4 shadow">
                        <div class="card-header text-body-secondary py-0 px-2 d-flex">
                            <span class="ms-auto">{{ post.vote_rating }} <i class="bi bi-stars"></i></span>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">
                                <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
                            </h5>
                            {% comment %} <h6 class="card-subtitle mb-2 text-body-secondary">{{ post.author.username }}</h6> {% endcomment %}
                        </div>
                        <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">
                            <i class="bi bi-chat-left-text mx-2"></i>
                            <span>{{ comment_count_list|dict_lookup:post.id }}</span>

                            {% if user.is_authenticated and post.author == user %}
                                <i class="bi bi-pencil-square mx-2"></i>
                                <a class="link-underline link-underline-opacity-0 p-0 m-0" href="{% url 'posts:edit' post.id %}">Edit</a>

                                <i class="bi bi-x-square mx-2"></i>
                                <form class="form-inline p-0 m-0 d-flex" id="deleteForm" action="{% url 'posts:delete' post.id %}" method="get">
                                    {% csrf_token %}
                                    <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteForm').submit();" style="cursor: pointer;">Delete</a>
                                </form>
                            {% endif %}

                            <span class="ms-auto">{{ post.pub_date }}</span>
                        </div>
                    </div>
                    {% endfor %}

                {% else %}
                    <div class="row my-4 shadow p-4 text-center">No threads yet.</div>
                {% endif %}

                </div>

                {% comment %} Comments {% endcomment %}

                <div class="tab-pane fade" id="comments-tab-pane" role="tabpanel" aria-labelledby="comments-tab" tabindex="0">

                {% if comments %}
                {% load template_filters %}

                {% for comment in comments %}
                
                <div class="row my-4">
                    <div class="col-auto">
                        <i class="bi bi-chat-left-text"></i>
                    </div>

                    <div class="col card shadow m-0 p-0">
                        <div class="card-header text-body-secondary py-0 px-2 d-flex">
                            <span class="ms-2 me-1">...</span><a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' comment.parent_object.id %}"> {{ comment.parent_object.title }}</a>
                            <span class="ms-auto">{{ comment.vote_rating }} <i class="bi bi-stars"></i></span>
                        </div>
                        <div class="card-body">
                            {% comment %} <h6 class="card-subtitle mb-2 text-body-secondary">{{ comment.author.username }}</h6> {% endcomment %}
                            <p class="card-text">{{ comment.content }}</p>
                        </div>
                        <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">

                            {% if user.is_authenticated and comment.author == user %}
                                <i class="bi bi-pencil-square mx-2"></i>
                                <a class="link-underline link-underline-opacity-0" href="{% url 'posts:edit_comment' comment.parent_object.id comment.id %}">Edit</a>
        
                                <i class="bi bi-x-square mx-2"></i>
                                <form class="form-inline p-0 m-0 d-flex" id="deleteCommentForm" action="{% url 'posts:delete_comment' comment.parent_object.id comment.id %}" method="get">
                                    {% csrf_token %}
                                    <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteCommentForm').submit();" style="cursor: pointer;">Delete</a>
                                </form>
                            {% endif %}
                            
                            <span class="ms-auto">{{ comment.pub_date }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %}

                {% else %}
                    <div class="row my-4 shadow p-4 text-center">No comments yet.</div>
                {% endif %}

                </div>

                {% comment %} Votes {% endcomment %}

                <div class="tab-pane fade" id="votes-tab-pane" role="tabpanel" aria-labelledby="votes-tab" tabindex="0">

                {% if votes %}
                {% load template_filters %}

                {% for vote in votes %}
                <div class="row my-4">

                    {% if vote.vote_type %}
                    <div class="col-auto">
                        <i class="text-success bi bi-hand-thumbs-up"></i>
                    </div>
                    {% else %}
                    <div class="col-auto">
                        <i class="text-danger bi bi-hand-thumbs-down"></i>
                    </div>
                    {% endif %}

                    {% if not vote.voted_object.title %}
                    <div class="col-auto">
                        <i class="bi bi-chat-left-text"></i>
                    </div>
                    {% endif %}

                    <div class="col card shadow m-0 p-0">

                        <div class="card-header text-body-secondary py-0 px-2 d-flex">

                            {% if not vote.voted_object.title %}
                            <span class="ms-2 me-1">...</span><a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' vote.voted_object.parent_object.id %}"> {{ vote.voted_object.parent_object.title }}</a>
                            {% endif %}

                            <span class="ms-auto">{{ vote.voted_object.vote_rating }} <i class="bi bi-stars"></i></span>
                            
                        </div>
                        <div class="card-body">

                            {% if vote.voted_object.title %}
                            <h5 class="card-title">
                                <a class="link-underline link-underline-opacity-0" href="{% url 'posts:detail' vote.voted_object.id %}">{{ vote.voted_object.title }}</a>
                            </h5>
                            {% endif %}

                            <h6 class="card-subtitle mb-2 text-body-secondary">
                                <a class="link-underline link-underline-opacity-0" href="{% url 'accounts:profile' vote.voted_object.author.slug %}">{{ vote.voted_object.author.username }}</a>
                            </h6>

                            {% if not vote.voted_object.title %}
                            <p class="card-text">{{ vote.voted_object.content }}</p>
                            {% endif %}
                        </div>
                        <div class="card-footer text-body-secondary text-end py-0 px-2 d-flex">

                            {% if user.is_authenticated and vote.voted_object.author == user %}

                                {% if vote.voted_object.title %}

                                    <i class="bi bi-pencil-square mx-2"></i>
                                    <a class="link-underline link-underline-opacity-0 p-0 m-0" href="{% url 'posts:edit' vote.voted_object.id %}">Edit</a>

                                    <i class="bi bi-x-square mx-2"></i>
                                    <form class="form-inline p-0 m-0 d-flex" id="deleteForm" action="{% url 'posts:delete' vote.voted_object.id %}" method="get">
                                        {% csrf_token %}
                                        <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteForm').submit();" style="cursor: pointer;">Delete</a>
                                    </form>

                                {% else %}
                                
                                    <i class="bi bi-pencil-square mx-2"></i>
                                    <a class="link-underline link-underline-opacity-0" href="{% url 'posts:edit_comment' vote.voted_object.parent_object.id vote.voted_object.id %}">Edit</a>
            
                                    <i class="bi bi-x-square mx-2"></i>
                                    <form class="form-inline p-0 m-0 d-flex" id="deleteCommentForm" action="{% url 'posts:delete_comment' vote.voted_object.parent_object.id vote.voted_object.id %}" method="get">
                                        {% csrf_token %}
                                        <a class="link-underline link-underline-opacity-0 p-0 m-0" onclick="document.getElementById('deleteCommentForm').submit();" style="cursor: pointer;">Delete</a>
                                    </form>
                                
                                {% endif %}

                            {% endif %}

                            <span class="ms-auto">{{ vote.voted_object.pub_date }}</span>
                        </div>
                    </div>
                </div>
                {% endfor %}

                {% else %}
                    <div class="row my-4 shadow p-4 text-center">No votes yet.</div>
                {% endif %}

                </div>
            </div>
        </div>

        {% else %}
        <div class="row my-4 shadow p-4 text-center">Please sign in to view profile.</div>
        {% endif %}

    </div>
</div>
{% endblock content %}

backend/accounts/templates/accounts/sign_in.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Sign In{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">

        {% if messages %}
            {% for message in messages %}
            {% comment %} {% if not "search_form_value" in message.tags %} {% endcomment %}
            <div class="row card my-2 border-danger">
                <div class="card-body">
                    <p class="card-text">{{ message }}</p>
                </div>
            </div>
            {% comment %} {% endif %} {% endcomment %}
            {% endfor %}
        {% endif %}

        <h3 class="text-center m-4">Sign In</h3>
        <form method="post">
            {% csrf_token %}
            <div class="form-floating my-3">
                {% if form.login_cred.value %}
                    {% if form.login_cred.errors %}
                    <input type="text" class="form-control is-invalid" id="{{ form.login_cred.id_for_label }}" name="{{ form.login_cred.html_name }}" value="{{ form.login_cred.value }}" placeholder="" required>
                    <div class="invalid-feedback">{{ form.login_cred.errors.0 }}</div>              
                    {% else %}
                    <input type="text" class="form-control" id="{{ form.login_cred.id_for_label }}" name="{{ form.login_cred.html_name }}" value="{{ form.login_cred.value }}" placeholder="" required>
                    {% endif %}
                {% else %}
                <input type="text" class="form-control" id="{{ form.login_cred.id_for_label }}" name="{{ form.login_cred.html_name }}" placeholder="" required>
                {% endif %}
                <label for="{{ form.login_cred.id_for_label }}">E-mail or Username</label>
            </div>

            <div class="form-floating my-3">
                {% if form.password.value %}
                    {% if form.password.errors %}
                    <input type="password" class="form-control is-invalid" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" value="{{ form.password.value }}" placeholder="" required>
                    <div class="invalid-feedback">{{ form.password.errors.0 }}</div> 
                    {% else %}
                    <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" value="{{ form.password.value }}" placeholder="" required>
                    {% endif %}
                {% else %}
                <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" placeholder="" required>
                {% endif %}
                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
            </div>
            
            <input class="btn btn-primary" type="submit" value="Sign In">
        </form>

    </div>
</div>
{% endblock content %}

backend/accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% block title %}ThreadMill - Sign Up{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        <h3 class="text-center m-4">Create an Account</h3>
        <form method="post">
            {% csrf_token %}

            <div class="form-floating my-3">
                {% if form.username.value %}
                    {% if form.username.errors %}
                    <input type="text" class="form-control is-invalid" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" value="{{ form.username.value }}" placeholder="" required aria-describedby="usernameHelp">
                    <div class="invalid-feedback">{{ form.username.errors.0 }}</div>              
                    {% else %}
                    <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" value="{{ form.username.value }}" placeholder="" required aria-describedby="usernameHelp">
                    {% endif %}
                {% else %}
                <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.html_name }}" placeholder="" required aria-describedby="usernameHelp">
                {% endif %}
                <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                <div id="usernameHelp" class="form-text">Posts you make will be displayed under this username.</div>
            </div>

            <div class="form-floating my-3">
                {% if form.email.value %}
                    {% if form.email.errors %}
                    <input type="email" class="form-control is-invalid" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" value="{{ form.email.value }}" placeholder="" required>
                    <div class="invalid-feedback">{{ form.email.errors.0 }}</div>              
                    {% else %}
                    <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" value="{{ form.email.value }}" placeholder="" required>
                    {% endif %}
                {% else %}
                <input type="email" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.html_name }}" placeholder="" required>
                {% endif %}
                <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            </div>

            <div class="form-floating my-3">
                {% if form.password.value %}
                    {% if form.password.errors %}
                    <input type="password" class="form-control is-invalid" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" value="{{ form.password.value }}" placeholder="" required>
                    <div class="invalid-feedback">{{ form.password.errors.0 }}</div> 
                    {% else %}
                    <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" value="{{ form.password.value }}" placeholder="" required>
                    {% endif %}
                {% else %}
                <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.html_name }}" placeholder="" required>
                {% endif %}
                <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
            </div>

            <div class="form-floating my-3">
                {% if form.confirm_password.value %}
                    {% if form.confirm_password.errors %}
                    <input type="password" class="form-control is-invalid" id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.html_name }}" value="{{ form.confirm_password.value }}" placeholder="" required>
                    <div class="invalid-feedback">{{ form.confirm_password.errors.0 }}</div> 
                    {% else %}
                    <input type="password" class="form-control" id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.html_name }}" value="{{ form.confirm_password.value }}" placeholder="" required>
                    {% endif %}
                {% else %}
                <input type="password" class="form-control" id="{{ form.confirm_password.id_for_label }}" name="{{ form.confirm_password.html_name }}" placeholder="" required>
                {% endif %}
                <label for="{{ form.confirm_password.id_for_label }}">{{ form.confirm_password.label }}</label>
            </div>
            
            <input class="btn btn-primary" type="submit" value="Sign Up">

        </form>
    </div>
</div>

{% endblock content %}