backend/accounts/urls.py
from django.urls import path
from .views import SignUpView, SignInView, SignOutView, ProfileView


app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="sign_up"),
    path("signin/", SignInView.as_view(), name="sign_in"),
    path("signout/", SignOutView.as_view(), name="sign_out"),
    path("profile/<slug:slug>", ProfileView.as_view(), name="profile"),
]

backend/posts/urls.py
from django.urls import path
from .views import (
    PostCreateView,
    PostIndexView,
    PostDetailView,
    voteView,
    PostEditView,
    CommentEditView,
    PostDeleteView,
    CommentDeleteView,
    SearchView,
)


app_name = "posts"
urlpatterns = [
    path("", PostIndexView.as_view(), name="index"),
    path("threads/new/", PostCreateView.as_view(), name="create"),
    path("threads/<int:pk>/", PostDetailView.as_view(), name="detail"),
    path(
        "threads/<int:post_id>/<int:id>/<int:content_type>/<int:vote_type>/<str:redir>/",
        voteView,
        name="vote",
    ),
    path("threads/<int:pk>/edit/", PostEditView.as_view(), name="edit"),
    path(
        "threads/<int:t_pk>/<int:pk>/edit/",
        CommentEditView.as_view(),
        name="edit_comment",
    ),
    path("threads/<int:pk>/delete/", PostDeleteView.as_view(), name="delete"),
    path(
        "threads/<int:t_pk>/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="delete_comment",
    ),
    path("search/", SearchView.as_view(), name="search"),
]

backend/threadmill/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("posts.urls")),
]

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ThreadMill{% endblock title %}</title>
    {% comment %} Include Bootstrap 5 styles and icons. {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
</head>
<body>
    {% comment %} Header {% endcomment %}

    <nav class="navbar navbar-expand-sm bg-body-tertiary">
        <div class="container-fluid d-flex">

            <a class="navbar-brand" href="{% url 'posts:index' %}">ThreadMill</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse flex-fill" id="collapsibleNavId">
                <div class="d-flex justify-content-between w-100">

                    <div class="navbar-nav px-5 mx-5"></div>
                    
                    <div class="navbar-nav mt-0 col-lg-5 me-2">
                        <form class="d-flex gap-2 w-100" role="search" action="{% url 'posts:search' %}" method="get">
                            <input class="form-control" type="search" name="search" placeholder="Search" value="{{ form.search.value }}" aria-label="Search">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>                    
                    </div>
                    
                    {% if not user.is_authenticated %}

                    <div class="navbar-nav gap-2">
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'posts:create' %}">New Thread</a>
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'accounts:sign_up' %}">Sign Up</a>
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'accounts:sign_in' %}">Sign In</a>
                    </div>

                    {% else %}

                    <div class="navbar-nav gap-2">
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'posts:create' %}">New Thread</a>
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'accounts:profile' user.slug %}">{{ user.username }}</a>
                        <a class="btn btn-outline-success my-sm-0 link-underline link-underline-opacity-0" href="{% url 'accounts:sign_out' %}">Sign Out</a>
                    </div>
                    
                    {% endif %}

                </div>

            </div>
        </div>
    </nav>
    
    {% block content %}{% endblock content %}

    {% comment %} Include Bootstrap 5 js. {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>